version: 2

sources:
  - name: weather
    database: snowflake_sample_data
  - name: tpch_sf1
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: customer
      - name: lineitem
      - name: nation
      - name: orders
      - name: part
      - name: partsupp
      - name: region
      - name: supplier
  - name: tpch_sf10
    database: snowflake_sample_data
    schema: tpch_sf10
    tables:
      - name: customer
      - name: lineitem
      - name: nation
      - name: orders
      - name: part
      - name: partsupp
      - name: region
      - name: supplier
  - name: tpch_sf100
    database: snowflake_sample_data
    schema: tpch_sf100
    tables:
      - name: customer
      - name: lineitem
      - name: nation
      - name: orders
      - name: part
      - name: partsupp
      - name: region
      - name: supplier
  - name: tpch_sf1000
    database: snowflake_sample_data
    schema: tpch_sf1000
    tables:
      - name: customer
      - name: lineitem
      - name: nation
      - name: orders
      - name: part
      - name: partsupp
      - name: region
      - name: supplier
